### ISSUE TITLE
[PD] Developers daily activities

### ISSUE THREAD

**Issue by sariat0001** [sariat0001/Induction#8]
From Induction created by [kfklein15](https://github.com/kfklein15): CodeYourFuture/Induction#3  

### Coursework content

Research a developer's daily activities and behaviours. What will you expect to know or do when you get your first job?  Activities are specific actions, tasks, or operations to accomplish a particular goal or objective.  For example: A marketing analyst must conduct market research and data analysis to identify consumer trends Behaviour is the observable actions, reactions, or conduct of someone.  For example: A marketing analyst must be able to effectively communicate complex data clearly and understandably to stakeholders.

### Estimated time in hours

1

### What is the purpose of this assignment?

- [ ]  Research a developer's daily activities and behaviours
- [ ]  Write at least 50 words on a Google Docs file
- [x] #9
- [ ]  Share the file with your cohort on the "Developers daily activities" thread. If the thread doesn't exist yet, create it.
- [ ]  Read two contents shared with you
- [ ]  Leave at least 2 comments or questions on each text you read

### How to submit

Add the link to your Google Docs
Add a screenshot of your post sharing your coursework

**Comment by sariat0001** [comment]
![Image](https://github.com/sariat0001/Induction/assets/115937264/6d2af396-e535-4e9e-ab18-19f11a7bf88e)

**Comment by sariat0001** [comment]
![Image](https://github.com/sariat0001/Induction/assets/115937264/28cb6380-e8d8-44fe-b497-fb36c6480055)

**Comment by kfklein15** [comment]
Again, no link to the doc or Slack to get to the doc.

**Comment by sariat0001** [comment]
Link to Google-doc

https://docs.google.com/document/d/1WayJ6k4iSRIq9LjGsYMMqNzETQye8NShekBk3gy08Ys/edit?usp=sharing

**Comment by sariat0001** [comment]
Link to slack

https://codeyourfuture.slack.com/archives/C05KCTSU67J/p1691148123106899?thread_ts=1690942657.821399&cid=C05KCTSU67J

**Comment by sariat0001** [comment]
@kfklein15 I am sorry for the error. It has been corrected. Thanks

**Comment by kfklein15** [comment]
Thank you. 
AI checker: 50% of AI
Grammarly: 37 alerts

This exercise was to write a short text - it says on the acceptance criteria 50 words. You wrote over 1k words. This in itself is a problem since if someone asks you to do one thing and you do something over the top, this is not helpful. What is the field only had 75 words? How would you rewrite it? 

The idea of these exercises is for you to practice writing English since you will have to do this on a daily basis. So, focus on trying and using your own knowledge and writing your own words of what you understand. 

There more your practice in a safe environment, the easier it will get.

**Comment by sariat0001** [comment]
I didn't read the instructions well. Hence, the error on my part. Subsequently, I will take into cognizance the essence of following instructions. Thanks

**Comment by sariat0001** [comment]
I'll re-write and submit. Thanks for the review.

**Comment by kfklein15** [comment]
@sariat0001 please don't forget to close this issue - otherwise it stays open and we will see it on our "mentioned/assigned" list forever :D
